### ISSUE TITLE
Обновление до 1.17 (Java 16)

### ISSUE THREAD

**Issue by WhiTe-Yak** [lokha/FiguresFix#2]
Сделайте обновление до актуальной версии игры с поддержкой новых более простых API.

**Comment by gomin1d** [comment]
Увы, но я не поддерживаю этот плагин.

**Comment by WhiTe-Yak** [comment]
> 
> 
> Увы, но я не поддерживаю этот плагин.

Совсем? Или возможно вернутся к разработке?

**Comment by gomin1d** [comment]
Это не мой плагин, я просто выложил его исходники.

Если мне лично потребуется поддержка java 16, я обновлю. Но пока что мне этого не надо, юзаю java 8.
